-- Q8 (negative). The operations generated by `genOps` are typed: closing a
-- `Temp.Chan 1` (one message still owed) is rejected.
module Main

import Language.Reflection

%language ElabReflection

genOps : TTImp -> Elab ()
genOps msg = declare `[
  public export
  data Chan : Nat -> Type where
    MkChan : List ~(msg) -> Chan n
  public export
  start : (n : Nat) -> Chan n
  start n = MkChan []
  public export
  send : Chan (S n) -> ~(msg) -> Chan n
  send (MkChan l) m = MkChan (m :: l)
  public export
  close : Chan 0 -> List ~(msg)
  close (MkChan l) = reverse l ]

namespace Temp
  %runElab genOps `(Nat)

bad : List Nat
bad = Temp.close (Temp.send (Temp.start 2) 20)
