#!/usr/bin/env bash
# Rerun case study A (vectors.lrl, its negative variants, corrected copies of the variants and
# the kernel-only checks) and write results_vectors.md next to this script.
#
# Usage:  case_studies/lrl/run_vectors.sh
# Env:    LRL           path of the LRL CLI binary (default: build it with `cargo build -p cli` and
#                       use ${CARGO_TARGET_DIR:-<repo>/target}/debug/cli)
#         CS_BUILD_DIR  directory for compiled binaries and logs (default: a fresh mktemp dir)
#         VECTORS_KERNEL_CHECK_TARGET_DIR  cargo target dir of the kernel-only harness
#                       (default: case_studies/tools/vectors_kernel_check/target)
#         SKIP_KERNEL_CHECK=1  skip the kernel-only harness
# The CLI is run from the repository root (it finds stdlib/ relative to the current directory).
# The typed backend writes its generated Rust into the repository's build/ (gitignored).
# Compatible with the macOS system bash (3.2).

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/results_vectors.md"
BUILD="${CS_BUILD_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/lrl_cs_vectors.XXXXXX")}"
LOGS="$BUILD/logs"
mkdir -p "$LOGS"
KC_DIR="$REPO/case_studies/tools/vectors_kernel_check"
KC_TARGET="${VECTORS_KERNEL_CHECK_TARGET_DIR:-$KC_DIR/target}"

if [ -z "${LRL:-}" ]; then
  (cd "$REPO" && cargo build -q -p cli) || { echo "cargo build -p cli failed" >&2; exit 1; }
  LRL="${CARGO_TARGET_DIR:-$REPO/target}/debug/cli"
fi

strip() { sed 's/\x1b\[[0-9;]*m//g'; }
esc() { sed 's/|/\\|/g'; }
first_error() {
  grep -m1 -E '^Error: \[[A-Z][0-9]+\]' "$1" | sed -E 's/^Error: \[([A-Z][0-9]+)\] (.*)$/\1	\2/'
}
rustc_errors() {
  local n first
  n=$(grep -c -E '^error\[E[0-9]+\]' "$1")
  first=$(grep -m1 -E '^error\[E[0-9]+\]' "$1")
  if [ "$n" -gt 0 ]; then echo "rustc: $n x \`$first\`"; fi
}
joined() { tr '\n' '/' < "$1" | sed 's#/$##; s#/# / #g'; }
cut_msg() { cut -c1-"${1:-240}"; }

cd "$REPO" || exit 1
SHA=$(shasum -a 256 "$LRL" | cut -c1-16)
P=case_studies/lrl/vectors.lrl

{
  echo "# Case study A — observed results"
  echo
  echo "Generated by \`case_studies/lrl/run_vectors.sh\` (do not edit by hand)."
  echo "CLI binary: \`$(basename "$LRL")\` (sha256 prefix \`$SHA\`). Date: $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "All commands are run from the repository root; ANSI colours stripped; long messages cut."
  echo
  echo "## Positive program \`$P\`"
  echo
  echo "| Command | CLI exit | Binary output (lines joined by \` / \`) or first error |"
  echo "|---|---|---|"
} > "$OUT"

# run (default dynamic backend): elaboration, kernel admission, MIR checks; does not execute main.
"$LRL" run "$P" > "$LOGS/run_dyn.log" 2>&1; ec=$?
strip < "$LOGS/run_dyn.log" > "$LOGS/run_dyn.txt"
e=$(first_error "$LOGS/run_dyn.txt" | tr '\t' ' ' | cut_msg | esc)
nax=$(grep -c -E "depends on (axioms|axiom)" "$LOGS/run_dyn.txt")
nbytes=$(wc -c < "$LOGS/run_dyn.txt" | tr -d ' ')
echo "| \`lrl run $P\` | $ec | ${e:-no error} ($nbytes bytes of output; lines mentioning axiom dependencies: $nax) |" >> "$OUT"

"$LRL" --require-axiom-tags run "$P" > "$LOGS/run_axtags.log" 2>&1; ec=$?
strip < "$LOGS/run_axtags.log" > "$LOGS/run_axtags.txt"
e=$(first_error "$LOGS/run_axtags.txt" | tr '\t' ' ' | cut_msg | esc)
nbytes=$(wc -c < "$LOGS/run_axtags.txt" | tr -d ' ')
echo "| \`lrl --require-axiom-tags run $P\` | $ec | ${e:-no error} ($nbytes bytes of output) |" >> "$OUT"

"$LRL" run "$P" --backend typed > "$LOGS/run_typed.log" 2>&1; ec=$?
strip < "$LOGS/run_typed.log" > "$LOGS/run_typed.txt"
if [ $ec -eq 0 ]; then
  grep -E '^[0-9]+$|^Result:' "$LOGS/run_typed.txt" > "$LOGS/run_typed.out"
  r=$(joined "$LOGS/run_typed.out")
else
  r=$(rustc_errors "$LOGS/run_typed.txt"); [ -z "$r" ] && r=$(first_error "$LOGS/run_typed.txt" | tr '\t' ' ' | cut_msg)
fi
echo "| \`lrl run $P --backend typed\` | $ec | $(echo "$r" | esc) |" >> "$OUT"

for backend in dynamic typed auto; do
  bin="$BUILD/vectors_$backend"
  rm -f "$bin"
  "$LRL" compile "$P" --backend "$backend" -o "$bin" > "$LOGS/compile_$backend.log" 2>&1; ec=$?
  strip < "$LOGS/compile_$backend.log" > "$LOGS/compile_$backend.txt"
  if [ $ec -eq 0 ] && [ -x "$bin" ]; then
    "$bin" > "$LOGS/bin_$backend.out" 2>&1; bec=$?
    r="$(joined "$LOGS/bin_$backend.out") (binary exit $bec)"
    w=$(grep -m1 -E '^Warning: rustc rejected typed backend output' "$LOGS/compile_$backend.txt" | sed -E 's/generated Rust kept at [^;]*; //')
    [ -n "$w" ] && r="$r; CLI: \`$w\`"
  else
    r=$(rustc_errors "$LOGS/compile_$backend.txt"); [ -z "$r" ] && r=$(first_error "$LOGS/compile_$backend.txt" | tr '\t' ' ' | cut_msg)
  fi
  echo "| \`lrl compile $P --backend $backend -o <bin>\` then \`<bin>\` | $ec | $(echo "$r" | esc) |" >> "$OUT"
done

# The rustc errors of the typed backend (if any), with the generated Rust function each one is in.
if grep -q -E '^error\[E[0-9]+\]' "$LOGS/compile_typed.txt"; then
{
  echo
  echo "### Typed backend: rustc errors of \`lrl compile $P --backend typed\`"
  echo
  echo "| rustc error | Generated Rust function containing it |"
  echo "|---|---|"
} >> "$OUT"
genrs=$(grep -m1 -o -E 'build/output_[0-9_]+\.rs' "$LOGS/compile_typed.txt")
if [ -n "$genrs" ] && [ -f "$genrs" ]; then
  # one line per rustc error: <error line> TAB <line in the generated .rs> TAB <first "expected ..." detail>
  awk '
    /^error\[E[0-9]+\]/ { if (err != "") print err "\t" loc "\t" det; err = $0; loc = ""; det = ""; next }
    err != "" && loc == "" && /--> build\/output_/ { s = $0; sub(/.*\.rs:/, "", s); sub(/:.*/, "", s); loc = s; next }
    err != "" && det == "" && /expected.*found/ { d = $0; sub(/^[ |^-]*/, "", d); det = d }
    END { if (err != "") print err "\t" loc "\t" det }
  ' "$LOGS/compile_typed.txt" | while IFS="$(printf '\t')" read -r err line detail; do
    fn=$(awk -v L="$line" 'NR<=L && /^(pub )?fn /{l=$0} NR==L{print l; exit}' "$genrs" | sed -E 's/^(pub )?fn ([A-Za-z0-9_]+).*/\2/')
    echo "| \`$err\` ($(echo "$detail" | cut_msg 160 | esc)) | \`$fn\` |" >> "$OUT"
  done
else
  echo "| (no generated Rust file found in the log) | |" >> "$OUT"
fi
fi

# ---------------------------------------------------------------------------------------------
# Negative variants: file | expected code | expected message fragment | what is wrong
# ---------------------------------------------------------------------------------------------
{
  echo
  echo "## Negative variants (\`case_studies/lrl/neg/vectors_*.lrl\`), \`lrl run <file>\`"
  echo
  echo "| File | What is wrong | Expected | CLI exit | Observed code | Observed message | Match |"
  echo "|---|---|---|---|---|---|---|"
} >> "$OUT"
NEGS='vectors_vhead_vnil.lrl|F0214|Unification failed: Nat.zero vs (Nat.succ|vhead applied to vnil
vectors_vappend_wrong_index.lrl|F0214|Unification failed|vappend whose vcons case drops the head
vectors_vappend_wrong_length.lrl|F0214|Unification failed|vappend v2 v2 (length 4) declared Vec Nat 3
vectors_false_vreverse_vsnoc.lrl|F0214|Unification failed|false lemma vreverse (vsnoc v x) = vcons x v with the proof of the true one
vectors_false_reverse_concrete.lrl|F0214|Unification failed|false equation vreverse [1, 2] = [1, 2] proved by refl
vectors_vmap_fnonce.lrl|F0206|Function kind mismatch|vmap with a #[once] function type (the vcons case consumes the captured f)
vectors_vtail_direct_generic.lrl|K0021|[RecursiveFieldConsumedByIh]|direct vtail for a generic element type (limitation, see README)'
echo "$NEGS" | while IFS='|' read -r file code frag what; do
  [ -z "$file" ] && continue
  f="case_studies/lrl/neg/$file"
  "$LRL" run "$f" < /dev/null > "$LOGS/$file.log" 2>&1; ec=$?
  strip < "$LOGS/$file.log" > "$LOGS/$file.txt"
  e=$(first_error "$LOGS/$file.txt")
  ocode=$(echo "$e" | cut -f1)
  omsg=$(echo "$e" | cut -f2-)
  ok=no
  if [ $ec -ne 0 ] && [ "$ocode" = "$code" ] && echo "$omsg" | grep -q -F "$frag"; then ok=yes; fi
  echo "| \`$file\` | $what | $code | $ec | $ocode | $(echo "$omsg" | cut_msg 300 | esc) | $ok |" >> "$OUT"
done

# ---------------------------------------------------------------------------------------------
# Corrected copies: each variant with its fault removed (a sed edit of the new code) is accepted.
# ---------------------------------------------------------------------------------------------
fix_variant() { # <file> <out>
  case "$(basename "$1")" in
    vectors_vhead_vnil.lrl) sed 's/(vhead (vnil {Nat}))/(vhead (vcons 1 (vnil {Nat})))/' "$1" > "$2" ;;
    vectors_vappend_wrong_index.lrl) sed 's/(case (vcons h t ih) ih)/(case (vcons h t ih) (vcons h ih))/' "$1" > "$2" ;;
    vectors_vappend_wrong_length.lrl) sed 's/(Vec Nat 3) (vappend/(Vec Nat 4) (vappend/' "$1" > "$2" ;;
    vectors_false_vreverse_vsnoc.lrl)
      sed -e 's/(vcons x v)/(vcons x (vreverse v))/' \
          -e 's/(vcons x w)/(vcons x (vreverse w))/' "$1" > "$2" ;;
    vectors_false_reverse_concrete.lrl)
      sed -e '/^  (Eq (Vec Nat 2) (vreverse/s/(vcons 1 (vcons 2 vnil)))$/(vcons 2 (vcons 1 vnil)))/' \
          -e '/^  (refl /s/(vcons 1 (vcons 2 vnil))))$/(vcons 2 (vcons 1 vnil))))/' "$1" > "$2" ;;
    vectors_vmap_fnonce.lrl) sed -e 's/(pi #\[once\] x A B)/(pi x A B)/g' -e 's/#\[once\] f /f /g' "$1" > "$2" ;;
    vectors_vtail_direct_generic.lrl) sed '/---- new code ----/,$ s/Vec A/Vec Nat/g' "$1" > "$2" ;;
    *) cp "$1" "$2" ;;
  esac
}
{
  echo
  echo "## Corrected copies of the negative variants (fault removed), \`lrl run <copy>\`"
  echo
  echo "| File | Correction | Changed lines | CLI exit | Errors |"
  echo "|---|---|---|---|---|"
} >> "$OUT"
FIXES='vectors_vhead_vnil.lrl|vhead of a 1-element vector
vectors_vappend_wrong_index.lrl|vcons case returns (vcons h ih)
vectors_vappend_wrong_length.lrl|declared type Vec Nat 4
vectors_false_vreverse_vsnoc.lrl|right-hand side vcons x (vreverse v) (the true lemma)
vectors_false_reverse_concrete.lrl|right-hand side and refl argument [2, 1]
vectors_vmap_fnonce.lrl|Fn function type (no #[once] on f and x A B)
vectors_vtail_direct_generic.lrl|element type Nat (Copy) instead of A'
echo "$FIXES" | while IFS='|' read -r file what; do
  [ -z "$file" ] && continue
  fixed="$BUILD/fixed_$file"
  fix_variant "case_studies/lrl/neg/$file" "$fixed"
  nchanged=$(diff "case_studies/lrl/neg/$file" "$fixed" | grep -c '^>')
  "$LRL" run "$fixed" < /dev/null > "$LOGS/fixed_$file.log" 2>&1; ec=$?
  nerr=$(strip < "$LOGS/fixed_$file.log" | grep -c -E '^Error')
  echo "| \`$file\` | $what | $nchanged | $ec | $nerr |" >> "$OUT"
done

# ---------------------------------------------------------------------------------------------
# The declarations above the "---- new code ----" line of every neg/vectors_*.lrl file must be
# copies of top-level forms of vectors.lrl (compared with comments removed, whitespace normalised).
# ---------------------------------------------------------------------------------------------
{
  echo
  echo "## Copied declarations"
  echo
  python3 - "$HERE" <<'PYEOF'
import glob, os, re, sys
here = sys.argv[1]
def forms(text):
    text = re.sub(r';[^\n]*', '', text)
    out, depth, cur = [], 0, ''
    for ch in text:
        if depth == 0 and ch != '(':
            continue
        cur += ch
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0:
                out.append(' '.join(re.findall(r'\(|\)|\{|\}|[^\s(){}]+', cur)))
                cur = ''
    return out
base = set(forms(open(os.path.join(here, 'vectors.lrl')).read()))
files = sorted(f for f in glob.glob(os.path.join(here, 'neg', 'vectors_*.lrl')) if not os.path.basename(f).startswith('._'))
bad = []
for f in files:
    head = open(f).read().split(';; ---- new code ----')[0]
    for form in forms(head):
        if form not in base:
            bad.append((os.path.relpath(f, here), form[:60]))
if bad:
    for f, form in bad:
        print('- MISMATCH `%s`: `%s ...`' % (f, form))
else:
    print('All %d variant files: every declaration above the `---- new code ----` line is a top-level form of vectors.lrl.' % len(files))
PYEOF
} >> "$OUT"

# ---------------------------------------------------------------------------------------------
# Kernel-only checks (case_studies/tools/vectors_kernel_check): axiom sets of the admitted
# theorems, the sort of their statements (Prop), independent re-check, and false statements
# submitted to the kernel directly.
# ---------------------------------------------------------------------------------------------
{
  echo
  echo "## Kernel-only checks (\`case_studies/tools/vectors_kernel_check\`)"
  echo
} >> "$OUT"
if [ "${SKIP_KERNEL_CHECK:-0}" = "1" ]; then
  echo "Skipped (SKIP_KERNEL_CHECK=1)." >> "$OUT"
else
  if ! CARGO_TARGET_DIR="$KC_TARGET" cargo build -q --offline --manifest-path "$KC_DIR/Cargo.toml" > "$LOGS/kc_build.log" 2>&1; then
    CARGO_TARGET_DIR="$KC_TARGET" cargo build -q --manifest-path "$KC_DIR/Cargo.toml" >> "$LOGS/kc_build.log" 2>&1
  fi
  if [ -x "$KC_TARGET/debug/vectors_kernel_check" ]; then
    "$KC_TARGET/debug/vectors_kernel_check" "$P" > "$LOGS/kernel_check.log" 2>&1; ec=$?
    {
      echo "\`vectors_kernel_check $P\` exit status: $ec"
      echo
      echo '```'
      grep -E '^(DIAGNOSTICS|DIAG|THEOREM|SORT|CHECK|FAILURES)' "$LOGS/kernel_check.log" | sed -E 's/(Type mismatch: expected .{60}).*( \| match=)/\1 ...\2/'
      echo '```'
    } >> "$OUT"
  else
    echo "Build of the harness failed; see $LOGS/kc_build.log" >> "$OUT"
  fi
fi

echo "wrote $OUT (logs in $LOGS)"
