#!/usr/bin/env bash
# Rerun case study B (protocol.lrl, its negative variants and its "limits" programs) and write
# results_protocol.md next to this script.
#
# Usage:  case_studies/lrl/run_protocol.sh
# Env:    LRL        path of the LRL CLI binary (default: build it with `cargo build -p cli` and
#                    use ${CARGO_TARGET_DIR:-<repo>/target}/debug/cli)
#         CS_BUILD_DIR  directory for compiled binaries and logs (default: a fresh mktemp dir).
# The CLI is run from the repository root (it finds stdlib/ relative to the current directory).
# The typed backend writes its generated Rust into the repository's build/ (gitignored).
# Compatible with the macOS system bash (3.2).

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/results_protocol.md"
BUILD="${CS_BUILD_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/lrl_cs_protocol.XXXXXX")}"
LOGS="$BUILD/logs"
mkdir -p "$LOGS"

if [ -z "${LRL:-}" ]; then
  (cd "$REPO" && cargo build -q -p cli) || { echo "cargo build -p cli failed" >&2; exit 1; }
  LRL="${CARGO_TARGET_DIR:-$REPO/target}/debug/cli"
fi

strip() { sed 's/\x1b\[[0-9;]*m//g'; }
esc() { sed 's/|/\\|/g'; }

# first "Error: [CODE] message" line of a log -> "CODE<TAB>message"
first_error() {
  grep -m1 -E '^Error: \[[A-Z][0-9]+\]' "$1" | sed -E 's/^Error: \[([A-Z][0-9]+)\] (.*)$/\1	\2/'
}
# rustc errors of a log: "<count> x <first error line>"
rustc_errors() {
  local n first
  n=$(grep -c -E '^error\[E[0-9]+\]' "$1")
  first=$(grep -m1 -E '^error\[E[0-9]+\]' "$1")
  if [ "$n" -gt 0 ]; then echo "rustc: $n x \`$first\`"; fi
}
macro_labels() {
  grep -o -E "(macro '[^']+' expanded here|in code produced by macro '[^']+')" "$1" | sort -u | tr '\n' ';' | sed 's/;$//; s/;/; /g'
}
# stdout lines of a binary, joined with " / "
joined() { tr '\n' '/' < "$1" | sed 's#/$##; s#/# / #g'; }

cd "$REPO" || exit 1
SHA=$(shasum -a 256 "$LRL" | cut -c1-16)

{
  echo "# Case study B — observed results"
  echo
  echo "Generated by \`case_studies/lrl/run_protocol.sh\` (do not edit by hand)."
  echo "CLI binary: \`$(basename "$LRL")\` (sha256 prefix \`$SHA\`). Date: $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "All commands are run from the repository root; ANSI colours stripped."
  echo
  echo "## Positive program \`case_studies/lrl/protocol.lrl\`"
  echo
  echo "| Command | CLI exit | Binary output (lines joined by \` / \`) or first error |"
  echo "|---|---|---|"
} > "$OUT"

P=case_studies/lrl/protocol.lrl
# run (default dynamic backend: kernel + MIR checks, evaluates top-level expressions only)
"$LRL" run "$P" > "$LOGS/run_dyn.log" 2>&1; ec=$?
strip < "$LOGS/run_dyn.log" > "$LOGS/run_dyn.txt"
e=$(first_error "$LOGS/run_dyn.txt")
[ -n "$e" ] && e=$(echo "$e" | tr '\t' ' ' | esc)
echo "| \`lrl run $P\` | $ec | ${e:-no error, no output (\`run\` without \`--backend typed\` does not execute \`main\`)} |" >> "$OUT"

# run --backend typed
"$LRL" run "$P" --backend typed > "$LOGS/run_typed.log" 2>&1; ec=$?
strip < "$LOGS/run_typed.log" > "$LOGS/run_typed.txt"
if [ $ec -eq 0 ]; then
  grep -v -E '^(Compiling|Running|Compilation|warning|note|  )' "$LOGS/run_typed.txt" | grep -E '^[0-9]+$|^Result:' > "$LOGS/run_typed.out"
  r=$(joined "$LOGS/run_typed.out")
else
  r=$(rustc_errors "$LOGS/run_typed.txt"); [ -z "$r" ] && r=$(first_error "$LOGS/run_typed.txt")
fi
echo "| \`lrl run $P --backend typed\` | $ec | $(echo "$r" | esc) |" >> "$OUT"

for backend in dynamic typed auto; do
  bin="$BUILD/protocol_$backend"
  rm -f "$bin"
  "$LRL" compile "$P" --backend "$backend" -o "$bin" > "$LOGS/compile_$backend.log" 2>&1; ec=$?
  strip < "$LOGS/compile_$backend.log" > "$LOGS/compile_$backend.txt"
  if [ $ec -eq 0 ] && [ -x "$bin" ]; then
    "$bin" > "$LOGS/bin_$backend.out" 2>&1; bec=$?
    r="$(joined "$LOGS/bin_$backend.out") (binary exit $bec)"
    w=$(grep -m1 -E '^Warning: rustc rejected typed backend output' "$LOGS/compile_$backend.txt" | sed -E 's/generated Rust kept at [^;]*; //')
    [ -n "$w" ] && r="$r; CLI: \`$w\`"
  else
    r=$(rustc_errors "$LOGS/compile_$backend.txt"); [ -z "$r" ] && r=$(first_error "$LOGS/compile_$backend.txt")
  fi
  echo "| \`lrl compile $P --backend $backend -o <bin>\` then \`<bin>\` | $ec | $(echo "$r" | esc) |" >> "$OUT"
done

# ---------------------------------------------------------------------------------------------
# Negative variants: file | expected code | expected message fragment | what is wrong
# ---------------------------------------------------------------------------------------------

{
  echo
  echo "## Negative variants (\`case_studies/lrl/neg/\`), \`lrl run <file>\`"
  echo
  echo "| File | What is wrong | Expected | CLI exit | Observed code | Observed message | Macro labels | Match |"
  echo "|---|---|---|---|---|---|---|---|"
} >> "$OUT"
while IFS='|' read -r file code frag what; do
  [ -z "$file" ] && continue
  f="case_studies/lrl/neg/$file"
  "$LRL" run "$f" < /dev/null > "$LOGS/$file.log" 2>&1; ec=$?
  strip < "$LOGS/$file.log" > "$LOGS/$file.txt"
  e=$(first_error "$LOGS/$file.txt")
  ocode=$(echo "$e" | cut -f1)
  omsg=$(echo "$e" | cut -f2-)
  labels=$(macro_labels "$LOGS/$file.txt")
  ok=no
  if [ $ec -ne 0 ] && [ "$ocode" = "$code" ] && echo "$omsg" | grep -q -F "$frag"; then ok=yes; fi
  echo "| \`$file\` | $what | $code | $ec | $ocode | $(echo "$omsg" | esc) | ${labels:--} | $ok |" >> "$OUT"
done <<'EOF'
protocol_send_twice.lrl|K0021|variable 'c' is used after it was moved|second send on the same channel value
protocol_send_twice_macro.lrl|K0021|variable 'c' is used after it was moved|the same double use, produced by a macro
protocol_use_after_branch.lrl|K0021|variable 'c' is used after it was moved|channel used after a branch of a Bool match consumed it
protocol_send_on_closed.lrl|F0214|Unification failed: Nat.zero vs (Nat.succ|send on a Chan zero
protocol_close_early.lrl|F0214|Unification failed|close a channel with a message left
protocol_send_all_wrong_length.lrl|F0214|Unification failed|send_all: Vec Nat 2 for a Chan 3
protocol_capture_by_hand.lrl|K0003|Expected function type, got App(Ind("List", []), Ind("Nat", []))|defsend's expansion pasted as text: `log` captured
protocol_send_not_once.lrl|F0206|Function kind mismatch: expected Fn, got FnOnce|defsend without #[once]: the closure owning the channel declared Fn
EOF

# ---------------------------------------------------------------------------------------------
# Corrected copies: each negative variant with its fault removed (a sed edit of the new code
# below the "---- new code ----" line) must be accepted.
# ---------------------------------------------------------------------------------------------
fix_variant() { # <file> <out>
  case "$(basename "$1")" in
    protocol_send_twice.lrl)
      sed '/---- new code ----/,$ s/(let r Receipt (close (send c 7))/(let r Nat zero/' "$1" > "$2" ;;
    protocol_send_twice_macro.lrl)
      sed '/---- new code ----/,$ s/(let r Receipt (close (send ch v))/(let r Nat zero/' "$1" > "$2" ;;
    protocol_use_after_branch.lrl)
      sed '/---- new code ----/,$ s/(close (send (send c 2) 3))/(close (send c1 3))/' "$1" > "$2" ;;
    protocol_send_on_closed.lrl)
      sed '/---- new code ----/,$ s/(Chan zero)/(Chan 1)/g' "$1" > "$2" ;;
    protocol_close_early.lrl)
      sed '/---- new code ----/,$ s/(close (send c 7))/(close (send (send c 7) 8))/' "$1" > "$2" ;;
    protocol_send_all_wrong_length.lrl)
      sed '/---- new code ----/,$ s/(vcons 7 (vcons 8 vnil))/(vcons 7 (vcons 8 (vcons 9 vnil)))/' "$1" > "$2" ;;
    protocol_capture_by_hand.lrl)
      sed '/---- new code ----/,$ s/(case (mk_chan log) (mk_chan (cons (log x) log)))/(case (mk_chan lg) (mk_chan (cons (log x) lg)))/' "$1" > "$2" ;;
    protocol_send_not_once.lrl)
      sed -e '/---- new code ----/,$ s/(pi x payload/(pi #[once] x payload/' \
          -e '/---- new code ----/,$ s/(lam x payload/(lam #[once] x payload/' "$1" > "$2" ;;
    *) cp "$1" "$2" ;;
  esac
}
{
  echo
  echo "## Corrected copies of the negative variants (fault removed), \`lrl run <copy>\`"
  echo
  echo "| File | Correction | Changed lines | CLI exit | Errors |"
  echo "|---|---|---|---|---|"
} >> "$OUT"
while IFS='|' read -r file what; do
  [ -z "$file" ] && continue
  fixed="$BUILD/fixed_$file"
  fix_variant "case_studies/lrl/neg/$file" "$fixed"
  nchanged=$(diff "case_studies/lrl/neg/$file" "$fixed" | grep -c '^>')
  "$LRL" run "$fixed" < /dev/null > "$LOGS/fixed_$file.log" 2>&1; ec=$?
  nerr=$(strip < "$LOGS/fixed_$file.log" | grep -c -E '^Error')
  echo "| \`$file\` | $what | $nchanged | $ec | $nerr |" >> "$OUT"
done <<'EOF'
protocol_send_twice.lrl|one send: the first `(close (send c 7))` replaced by `zero`
protocol_send_twice_macro.lrl|the template mentions its channel argument once
protocol_use_after_branch.lrl|`(close (send c1 3))`: the channel returned by the match
protocol_send_on_closed.lrl|the channel has type `Chan 1`
protocol_close_early.lrl|two sends before `close`
protocol_send_all_wrong_length.lrl|a 3-element vector
protocol_capture_by_hand.lrl|the pattern variable renamed `lg` (as the hygienic expansion does)
protocol_send_not_once.lrl|`#[once]` restored on the payload binder
EOF

# ---------------------------------------------------------------------------------------------
# Limits: programs that are ACCEPTED although they break the protocol's intent.
# ---------------------------------------------------------------------------------------------
{
  echo
  echo "## Not enforced (\`case_studies/lrl/limits/\`): accepted programs"
  echo
  echo "| File | \`lrl run\` exit | \`compile --backend dynamic\` exit | Binary output |"
  echo "|---|---|---|---|"
} >> "$OUT"
for f in case_studies/lrl/limits/protocol_*.lrl; do
  case "$(basename "$f")" in ._*) continue ;; esac
  b=$(basename "$f" .lrl)
  "$LRL" run "$f" > "$LOGS/$b.run.log" 2>&1; ec=$?
  bin="$BUILD/$b"
  rm -f "$bin"
  "$LRL" compile "$f" --backend dynamic -o "$bin" > "$LOGS/$b.compile.log" 2>&1; cec=$?
  r="-"
  if [ $cec -eq 0 ] && [ -x "$bin" ]; then "$bin" > "$LOGS/$b.out" 2>&1; r="$(joined "$LOGS/$b.out") (binary exit $?)"; fi
  echo "| \`$f\` | $ec | $cec | $(echo "$r" | esc) |" >> "$OUT"
done

# ---------------------------------------------------------------------------------------------
# The declarations above the "---- new code ----" line of every neg/ and limits/ file must be
# copies of top-level forms of protocol.lrl (compared with comments removed, whitespace
# normalised), so that the variants test the same protocol as the positive program.
# ---------------------------------------------------------------------------------------------
{
  echo
  echo "## Copied declarations"
  echo
  python3 - "$HERE" <<'PYEOF'
import glob, os, re, sys
here = sys.argv[1]
def forms(text):
    text = re.sub(r';[^\n]*', '', text)
    out, depth, cur = [], 0, ''
    for ch in text:
        if depth == 0 and ch != '(':
            continue
        cur += ch
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0:
                out.append(' '.join(re.findall(r'\(|\)|\{|\}|[^\s(){}]+', cur)))
                cur = ''
    return out
base = set(forms(open(os.path.join(here, 'protocol.lrl')).read()))
bad = []
files = sorted(glob.glob(os.path.join(here, 'neg', 'protocol_*.lrl')) + glob.glob(os.path.join(here, 'limits', 'protocol_*.lrl')))
files = [f for f in files if not os.path.basename(f).startswith('._')]
for f in files:
    text = open(f).read()
    head = text.split(';; ---- new code ----')[0]
    for form in forms(head):
        if form not in base:
            bad.append((os.path.relpath(f, here), form[:60]))
if bad:
    for f, form in bad:
        print('- MISMATCH `%s`: `%s ...`' % (f, form))
else:
    print('All %d variant files: every declaration above the `---- new code ----` line is a top-level form of protocol.lrl.' % len(files))
PYEOF
} >> "$OUT"

echo "wrote $OUT (logs in $LOGS)"
