/-!
Q8 (negative). The operations generated by the `protocol` macro are typed: closing a
`Temp.Chan 1` (one message still owed) is rejected.
-/
open Lean in
macro "protocol " name:ident " carrying " msg:term : command => do
  let chan  := mkIdentFrom name (name.getId ++ `Chan)
  let start := mkIdentFrom name (name.getId ++ `start)
  let send  := mkIdentFrom name (name.getId ++ `send)
  let close := mkIdentFrom name (name.getId ++ `close)
  `(structure $chan (n : Nat) where
      sent : List $msg
    def $start (n : Nat) : $chan n := ⟨[]⟩
    def $send {n : Nat} (c : $chan (n + 1)) (m : $msg) : $chan n := ⟨m :: c.sent⟩
    def $close (c : $chan 0) : List $msg := c.sent.reverse)

protocol Temp carrying Nat

def bad : List Nat := Temp.close (Temp.send (Temp.start 2) 20)
